baseURL: https://wonyoungjang.org/
title: Wonyoung Jang

# languageCode: en-US

description: "Wonyoung Jang's personal website"
copyright: <!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->

enableRobotsTXT: true
enableGitInfo: true

# Outputs
outputs:
  home:
    - HTML
    - RSS
    - JSON
  taxonomy:
    - HTML
    - RSS
  term:
    - HTML
    - RSS

# Services
services:
  googleAnalytics: 
    ID: G-RTMKJG4NFZ

# Sitemap
sitemap:
  filename: sitemap.xml
  priority: 0.5
  changefreq: daily

# Taxonomies
taxonomies:
  project: projects
  resource: resources

####################
# All root configs #
####################

# build:
# caches:
# cascade:
# deployment:
# frontmatter:
# httpcache:
# imaging:
# languages:
#   en:
#     menus:
#     params:
# markup: → markup.yaml
# mediatypes:
# menus: → menus.yaml
# minify:
# module:
# outputformats:
# outputs:
# params: → params.yaml
# permalinks:
# privacy:
# related: → related.yaml
# security:
# segments:
# server:
# services:
# sitemap:
# taxonomies:
