baseURL: https://wonyoungjang.org/
title: Wonyoung Jang

# languageCode: en-US

description: "Wonyoung Jang's personal website"
copyright: <!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->

enableRobotsTXT: true
enableGitInfo: true

taxonomies:
  keyword: keywords

####################
# All root configs #
####################

# build:
# caches:
# cascade:
# deployment:
# frontmatter:
# httpcache:
# imaging: → imaging.yaml
# languages:
#   en:
#     menus:
#     params:
# markup: → markup.yaml
# mediatypes:
# menus: → menus.yaml
# minify:
# module:
# outputformats:
# outputs: → outputs.yaml
# params: → params.yaml
# permalinks:
# privacy:
# related: → related.yaml
# security:
# segments:
# server:
# services: → services.yaml
# sitemap: → sitemap.yaml
# taxonomies:
