baseURL: https://wonyoungjang.org/
title: Wonyoung Jang
paginate: 9

# enableRobotsTXT: Specifies whether to generate a robots.txt file for the site.
# buildDrafts: Specifies whether to include draft content in the site build.
# buildFuture: Specifies whether to include future-dated content in the site build.
# buildExpired: Specifies whether to include expired content in the site build.
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: true

googleAnalytics: G-RTMKJG4NFZ

minify:
  disableXML: true
  minifyOutput: true

disableKinds:
- taxonomy
- term

# Ignore files
ignoreFiles:
  \.zip$

# Sitemap
sitemap:
  filename: sitemap.xml
  priority: 0.5
  changefreq: daily

# See Also
related:
  includeNewer: true
  indices:
  - applyFilter: true
    name: categories
    weight: 80
  threshold: 20

# Output formats
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
    - JSON


####################
# DISABLED CONFIGS #
####################

# taxonomies:
#   category: "categories"