baseURL: https://wonyoungjang.org/
title: Wonyoung Jang
paginate: 9

# enableRobotsTXT: Specifies whether to generate a robots.txt file for the site.
# buildDrafts: Specifies whether to include draft content in the site build.
# buildFuture: Specifies whether to include future-dated content in the site build.
# buildExpired: Specifies whether to include expired content in the site build.
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: true

# sectionPagesMenu: main

googleAnalytics: G-RTMKJG4NFZ

minify:
  disableXML: true
  minifyOutput: true

disableKinds:
- taxonomy
- term

# Ignore files
ignoreFiles:
  \.zip$

# Sitemap
sitemap:
  filename: sitemap.xml
  priority: 0.5
  changefreq: daily

# See Also
related:
  includeNewer: false
  indices:
  - applyFilter: false
    cardinalityThreshold: 0
    name: keywords
    pattern: ""
    toLower: false
    type: basic
    weight: 100
  - applyFilter: false
    cardinalityThreshold: 0
    name: date
    pattern: ""
    toLower: false
    type: basic
    weight: 10
  - applyFilter: false
    cardinalityThreshold: 0
    name: tags
    pattern: ""
    toLower: false
    type: basic
    weight: 80
  threshold: 80
  toLower: false

# Output formats
outputs:
  home:
    - HTML
    - RSS
    - JSON


####################
# DISABLED CONFIGS #
####################

# taxonomies:
#   category: "categories"

# The root configuration keys are 
  # build, 
  # caches, 
  # cascade,
  # deployment, 
  # frontmatter,
  # imaging,
  # languages, 
  # markup DONE
  # mediatypes,
  # menus DONE
  # minify, 
  # module,
  # outputformats,
  # outputs,
  # params DONE 
  # permalinks,
  # privacy,
  # related,
  # security,
  # segments,
  # server, 
  # services,
  # sitemap,
  # taxonomies