baseURL: https://wonyoungjang.org/
copyright: <!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->
enableGitInfo: true
enableRobotsTXT: true
languageCode: en-US
theme: github.com/wonyoung-jang/hugo-PolyRhythmic
title: Wonyoung Jang

################
# KEY SETTINGS #
################

# build:
# caches:
# cascade:
# deployment:
# frontmatter:
# httpcache:
# imaging:
# languages:
#   en:
#     menus:
#     params:
# markup: → markup.yaml
# mediatypes:
# menus: → menus.yaml
# minify: → minify.yaml
# module:
# outputformats:
# outputs: → outputs.yaml
# params: → params.yaml
# permalinks:
# privacy:
# related:
# security:
# segments:
# server:
# services: → services.yaml
# sitemap: → sitemap.yaml
# taxonomies: → taxonomies.yaml
