baseURL: https://wonyoungjang.org/
title: Wonyoung Jang
languageCode: en-us

author: "Wonyoung Jang"

enableRobotsTXT: true

titleCaseStyle: ap

# Ignore files
ignoreFiles: 
- \.zip$

# Taxonomies
disableKinds:
- taxonomy
- term

####################
# All root configs #
####################

# build:
# caches:
# cascade:
# deployment:
# frontmatter:
# httpcache:
# imaging:
# languages:
#   en:
#     menus:
#     params:
# markup: → markup.yaml
# mediatypes:
# menus: → menus.yaml
# minify: → minify.yaml
# module:
# outputformats:
# outputs: → outputs.yaml
# params: → params.yaml
# permalinks:
# privacy:
# related: → related.yaml
# security:
# segments:
# server:
# services: → services.yaml
# sitemap: → sitemap.yaml
# taxonomies:
