baseURL: https://wonyoungjang.org/
title: Wonyoung Jang

# languageCode: en-US

copyright: <!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->

enableRobotsTXT: true
enableGitInfo: true

# Markup
markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    tabWidth: 4
    style: github-dark

  tableOfContents:
    ordered: false
    startLevel: 1
    endLevel: 6
    
  goldmark:
    parser:
      wrapStandAloneImageWithinParagraph: false

# Outputs
outputs:
  home:
    - HTML
    - RSS
    - JSON
  taxonomy:
    - HTML
    - RSS
  term:
    - HTML
    - RSS

# Related
related:
  threshold: 10
  includeNewer: true

  indices:
    - name: title
      weight: 40
      type: basic
    - name: type
      weight: 30
      type: basic
    - name: description
      weight: 20
      type: basic
    - name: date
      weight: 10
      type: basic
      pattern: "2006"

# Services
services:
  googleAnalytics: 
    ID: G-RTMKJG4NFZ

# Sitemap
sitemap:
  filename: sitemap.xml
  priority: 0.5
  changefreq: daily

# Taxonomies
taxonomies:
  project: projects
  resource: resources

####################
# All root configs #
####################

# build:
# caches:
# cascade:
# deployment:
# frontmatter:
# httpcache:
# imaging:
# languages:
#   en:
#     menus:
#     params:
# markup:
# mediatypes:
# menus: → menus.yaml
# minify:
# module:
# outputformats:
# outputs:
# params: → params.yaml
# permalinks:
# privacy:
# related:
# security:
# segments:
# server:
# services:
# sitemap:
# taxonomies:
