highlight:
  lineNos: true
  style: github-dark
  tabWidth: 4

tableOfContents:
  startLevel: 1
  endLevel: 6
  ordered: false

defaultMarkdownHandler: goldmark

goldmark:
  renderHooks:
    image:
      enableDefault: true
    link:
      enableDefault: true
  parser:
    attribute:
      title: true
