highlight:
  anchorLineNos: true
  codeFences: true
  guessSyntax: true
  lineNos: true
  tabWidth: 4
  pygmentsUseClasses: true
  style: github-dark

defaultMarkdownHandler: goldmark

goldmark:
  renderHooks:
    image:
      enableDefault: true
    link:
      enableDefault: true
  parser:
    attribute:
      title: true

tableOfContents:
  ordered: false
  startLevel: 1
  endLevel: 6