highlight:
  anchorLineNos: true
  codeFences: true
  guessSyntax: true
  lineNos: true
  tabWidth: 4
  pygmentsUseClasses: true
  style: github-dark

tableOfContents:
  ordered: false
  startLevel: 1
  endLevel: 6