highlight:
  lineNos: true
  style: github-dark
  tabWidth: 4

defaultMarkdownHandler: goldmark

goldmark:
  renderHooks:
    image:
      enableDefault: true
    link:
      enableDefault: true
  parser:
    attribute:
      title: true

tableOfContents:
  ordered: false
  startLevel: 1
  endLevel: 6