main:
  - identifier: Projects
    name: Projects
    pageRef: /project
    pre: <i>code</i>
    weight: 10
  - identifier: Resource
    name: Resources
    pageRef: /resource
    pre: <i>developer_guide</i>
    weight: 20
  - identifier: Now
    name: Now
    pageRef: /now
    pre: <i>update</i>
    weight: 30

footer:
  - identifier: About
    name: About
    pageRef: /about
    weight: 10
  - identifier: Contact
    name: Contact
    pageRef: /contact
    weight: 20
  - identifier: Now
    name: Now
    pageRef: /now
    weight: 25
  - identifier: Search
    name: Search
    pageRef: /search
    weight: 30
  - identifier: Sitemap
    name: Sitemap
    pageRef: /sitemap
    weight: 40
  - identifier: RSS
    name: RSS
    url: https://wonyoungjang.org/index.xml
    weight: 50

connect:
  - name: GitHub
    url: https://github.com/wonyoung-jang
    weight: 10
    pre: <i>code</i>
  - name: Email
    url: mailto:contact@wonyoungjang.org
    weight: 20
    pre: <i>outgoing_mail</i>
  - name: Ko-fi
    url: https://ko-fi.com/wonyoung_jang
    weight: 30
    pre: <i>loyalty</i>

sections:
  - identifier: Projects
    name: Projects
    pageRef: /project
    weight: 10
  - identifier: Software
    name: Software
    pageRef: /software
    weight: 15
  - identifier: University
    name: University
    pageRef: /university
    weight: 17
  - name: Resources
    pageRef: /resource
    weight: 20
  - name: References
    pageRef: /reference
    weight: 25