main:
  - identifier: Projects
    name: Projects
    pageRef: /project
    pre: <i>code</i>
    weight: 10
  - name: Software
    pageRef: /project/software
    pre: <i>terminal</i>
    parent: Projects
    weight: 1
  - name: Designs
    pageRef: /project/design
    pre: <i>design_services</i>
    parent: Projects
    weight: 2
  - name: University
    pageRef: /project/university
    pre: <i>school</i>
    parent: Projects
    weight: 3
  - identifier: Resources
    name: Resources
    pageRef: /resource
    pre: <i>developer_guide</i>
    weight: 20
  - name: Layouts
    pageRef: /resource/layout
    pre: <i>quick_reference</i>
    parent: Resources
    weight: 1
  - name: References
    pageRef: /resource/reference
    pre: <i>quick_reference</i>
    parent: Resources
    weight: 2
  - name: Tokens
    pageRef: /resource/token
    pre: <i>quick_reference</i>
    parent: Resources
    weight: 3
  - identifier: Now
    name: Now
    pageRef: /now
    pre: <i>update</i>
    weight: 30

footer:
  - identifier: About
    name: About
    pageRef: /about
    weight: 10
  - identifier: Contact
    name: Contact
    pageRef: /contact
    weight: 20
  - identifier: Now
    name: Now
    pageRef: /now
    weight: 25
  - identifier: Search
    name: Search
    pageRef: /search
    weight: 30
  - identifier: Sitemap
    name: Sitemap
    pageRef: /sitemap
    weight: 40
  - identifier: RSS
    name: RSS
    url: https://wonyoungjang.org/index.xml
    weight: 50

sections:
  - identifier: Projects
    name: Projects
    pageRef: /project
    weight: 10
  - name: Software
    pageRef: /project/software
    weight: 1
    parent: Projects
  - name: University
    pageRef: /project/university
    weight: 2
    parent: Projects
  - identifier: Resources
    name: Resources
    pageRef: /resource
    weight: 20
  - name: Layouts
    pageRef: /resource/layout
    weight: 1
    parent: Resources
  - name: References
    pageRef: /resource/reference
    weight: 2
    parent: Resources
  - name: Tokens
    pageRef: /resource/token
    weight: 3
    parent: Resources

connect:
  - name: Email
    url: mailto:contact@wonyoungjang.org
    weight: 10
    pre: <i>outgoing_mail</i>
  - name: Figma
    url: https://www.figma.com/@wonyoung_jang
    weight: 20
    pre: <i>palette</i>
  - name: GitHub
    url: https://github.com/wonyoung-jang
    weight: 30
    pre: <i>code</i>
  - name: Ko-fi
    url: https://ko-fi.com/wonyoung_jang
    weight: 40
    pre: <i>loyalty</i>
