main:
  - identifier: Search
    name: Search
    pageRef: /search
    weight: 10
  - identifier: Projects # TODO This is a temporary hack
    name: Projects
    pageRef: /categories
    weight: 20
  - identifier: Software Development
    name: Software Development
    pageRef: /categories/software-development-projects
    parent: Projects
    weight: 1
  - identifier: University Coursework
    name: University Coursework
    pageRef: /categories/university-coursework-projects
    parent: Projects
    weight: 2
  - identifier: Graph
    name: Graph
    url: /graph/#/graph
    weight: 25
  - identifier: Archives
    name: Archives
    pageRef: /archives
    weight: 30
  - identifier: About
    name: About
    pageRef: /about
    weight: 50
  - identifier: Contact
    name: Contact
    pageRef: /contact
    weight: 60