main:
  - identifier: Projects
    name: Projects
    pageRef: /projects
    pre: <i>folder_shared</i>
    weight: 10
  - name: Designs
    pageRef: /projects/design
    pre: <i>design_services</i>
    parent: Projects
  - name: Software
    pageRef: /projects/software
    pre: <i>terminal</i>
    parent: Projects
  - name: University
    pageRef: /projects/university
    pre: <i>school</i>
    parent: Projects
  - identifier: Resources
    name: Resources
    pageRef: /resources
    pre: <i>library_books</i>
    weight: 20
  - name: Layouts
    pageRef: /resources/layouts
    pre: <i>view_quilt</i>
    parent: Resources
  - name: References
    pageRef: /resources/references
    pre: <i>bookmark_border</i>
    parent: Resources
  - name: Tokens
    pageRef: /resources/tokens
    pre: <i>token</i>
    parent: Resources
  - identifier: Now
    name: Now
    pageRef: /now
    pre: <i>update</i>
    weight: 30
  - identifier: Search
    name: Search
    pageRef: /search
    pre: <i>search</i>
    weight: 40

footer:
  - identifier: About
    name: About
    pageRef: /about
  - identifier: Contact
    name: Contact
    pageRef: /contact
  - identifier: Graph
    name: Graph
    pageRef: /graph
  - identifier: Now
    name: Now
    pageRef: /now
  - identifier: RSS
    name: RSS
    url: https://wonyoungjang.org/index.xml
  - identifier: Search
    name: Search
    pageRef: /search
  - identifier: Sitemap
    name: Sitemap
    pageRef: /sitemap

sections:
  - identifier: Projects
    name: Projects
    pageRef: /projects
  - name: Design
    pageRef: /projects/design
    parent: Projects
  - name: Software
    pageRef: /projects/software
    parent: Projects
  - name: University
    pageRef: /projects/university
    parent: Projects
  - identifier: Resources
    name: Resources
    pageRef: /resources
  - name: Layouts
    pageRef: /resources/layouts
    parent: Resources
  - name: References
    pageRef: /resources/references
    parent: Resources
  - name: Tokens
    pageRef: /resources/tokens
    parent: Resources

connect:
  - name: Email
    url: mailto:contact@wonyoungjang.org
  - name: Figma
    url: https://www.figma.com/@wonyoung_jang
  - name: GitHub
    url: https://github.com/wonyoung-jang
  - name: Ko-fi
    url: https://ko-fi.com/wonyoung_jang
