main:
  - identifier: Home
    name: Home
    pageRef: /
    weight: 1
  - identifier: Projects
    name: Projects
    url: /project
    weight: 10
  - identifier: Software
    name: Software
    pageRef: /project/software
    parent: Projects
    weight: 1
  - identifier: University
    name: University
    pageRef: /project/university
    parent: Projects
    weight: 2

  #- identifier: Articles
  #  name: Articles
  #  url: /article
  #  weight: 20

  - identifier: Resources
    name: Resources
    url: /resource
    weight: 30

  #- identifier: Updates
  #  name: Updates
  #  url: /update
  #  weight: 40

  - identifier: Archives
    name: Archives
    pageRef: /archives
    weight: 50
  - identifier: Search
    name: Search
    pageRef: /search
    weight: 60
  - identifier: Graph
    name: Graph
    url: /graph/#/graph
    weight: 70
