main:
  - identifier: Projects
    name: Projects
    pageRef: /projects
    pre: <i class="icon">folder_shared</i>
    weight: 10
  - name: Designs
    pageRef: /projects/design
    pre: <i class="icon">design_services</i>
    parent: Projects
  - name: Software
    pageRef: /projects/software
    pre: <i class="icon">terminal</i>
    parent: Projects
  - name: University
    pageRef: /projects/university
    pre: <i class="icon">school</i>
    parent: Projects

  - identifier: Resources
    name: Resources
    pageRef: /resources
    pre: <i class="icon">library_books</i>
    weight: 20
  - name: Components
    pageRef: /resources/components
    pre: <i class="icon">settings</i>
    parent: Resources
  - name: Layouts
    pageRef: /resources/layouts
    pre: <i class="icon">view_quilt</i>
    parent: Resources
  - name: References
    pageRef: /resources/references
    pre: <i class="icon">bookmark_border</i>
    parent: Resources
  - name: Tokens
    pageRef: /resources/tokens
    pre: <i class="icon">token</i>
    parent: Resources

  - identifier: Now
    name: Now
    pageRef: /now
    pre: <i class="icon">update</i>
    weight: 30

  - identifier: Search
    name: Search
    pageRef: /search
    pre: <i class="icon">search</i>
    weight: 40

footer:
  - identifier: About
    name: About
    pageRef: /about
  - identifier: Archives
    name: Archives
    pageRef: /archives
  - identifier: Contact
    name: Contact
    pageRef: /contact
  - identifier: Graph
    name: Graph
    pageRef: /graph
  - identifier: Now
    name: Now
    pageRef: /now
  - identifier: Playground
    name: Playground
    pageRef: /playground
  - identifier: RSS
    name: RSS
    url: https://wonyoungjang.org/index.xml
  - identifier: Search
    name: Search
    pageRef: /search
  - identifier: Sitemap
    name: Sitemap
    pageRef: /sitemap

projects:
  - name: Projects
    pageRef: /projects
    weight: 1
  - name: Design
    pageRef: /projects/design
  - name: Software
    pageRef: /projects/software
  - name: University
    pageRef: /projects/university

resources:
  - name: Resources
    pageRef: /resources
    weight: 1
  - name: Components
    pageRef: /resources/components
  - name: Layouts
    pageRef: /resources/layouts
  - name: References
    pageRef: /resources/references
  - name: Tokens
    pageRef: /resources/tokens

connect:
  - name: Email
    url: mailto:contact@wonyoungjang.org
  - name: Figma
    url: https://www.figma.com/@wonyoung_jang
  - name: GitHub
    url: https://github.com/wonyoung-jang
  - name: Ko-fi
    url: https://ko-fi.com/wonyoung_jang
