main:
  - identifier: Projects
    name: Projects
    pageRef: /project
    weight: 10
  - identifier: Resource
    name: Resources
    pageRef: /resource
    weight: 20

footer:
  - identifier: About
    name: About
    pageRef: /about
    weight: 10
  - identifier: Contact
    name: Contact
    pageRef: /contact
    weight: 20
  - identifier: Search
    name: Search
    pageRef: /search
    weight: 30
  - identifier: Sitemap
    name: Sitemap
    pageRef: /sitemap
    weight: 40
  - identifier: RSS
    name: RSS
    pageRef: /index.xml
    weight: 50