main:
  - identifier: Home
    name: Home
    pageRef: /
    weight: 1
  #- identifier: Search
  #  name: Search
  #  pageRef: /search
  #  weight: 10
  #- identifier: Projects
  #  name: Projects
  #  pageRef: /projects
  #  weight: 12
  - identifier: Category
    name: Category
    pageRef: /category
    weight: 14
  - identifier: Software Development Projects
    name: Software Development Projects
    pageRef: /category/software-development-projects
    parent: Category
    weight: 1
  - identifier: University Coursework Projects
    name: University Coursework Projects
    pageRef: /category/university-coursework-projects
    parent: Category
    weight: 2
  - identifier: Lists
    name: Lists
    pageRef: /category/lists
    parent: Category
    weight: 3
  - identifier: Meta
    name: Meta
    pageRef: /category/meta
    parent: Category
    weight: 4
  - identifier: Graph
    name: Graph
    url: /graph/#/graph
    weight: 20
  #- identifier: Archives
  #  name: Archives
  #  pageRef: /archives
  #  weight: 30
  #- identifier: About
  #  name: About
  #  pageRef: /about
  #  weight: 32
  #- identifier: Contact
  #  name: Contact
  #  pageRef: /contact
  #  weight: 34

  # - identifier: RSS
  #   name: RSS
  #   url: /index.xml
  #   weight: 70
