debug: false

defaultTheme: auto
env: production
title: Wonyoung Jang
dateFormat: January 2, 2006

assets:
  favicon: 'sitelogo.svg'

home:
  title: Wonyoung Jang
  tagline: exist on earth **∧** time **→** create
  blurb: |
    If I'm alive and have the time, then I'll create stuff and post it here.
    You are welcome to use anything you find here.


  projectButtons:
    - name: Software
      url: /projects/software
    - name: Design
      url: /projects/design
    - name: University
      url: /projects/university
  resourceButtons:
    - name: Layouts
      url: /resources/layouts
    - name: References
      url: /resources/references
    - name: Tokens
      url: /resources/tokens

author:
  name: Wonyoung Jang
  email: contact@wonyoungjang.org

fuseOpts:
  # Basic
  isCaseSensitive: false
  includeScore: true
  includeMatches: true
  minMatchCharLength: 1
  shouldSort: true
  findAllMatches: false
  keys: ["title", "permalink", "summary", "description", "content"]

  # Fuzzy matching
  location: 0
  threshold: 0.6
  distance: 100
  ignoreLocation: false

  limit: 5