debug: true

defaultTheme: auto
env: production
title: Wonyoung Jang

assets:
  favicon: '/sitelogo.svg'

label:
  icon: '/sitelogo.svg'
  iconHeight: 24

home:
  title: Wonyoung Jang
  subtitle: Personal Website

  buttons:
    - name: Software development projects
      url: "/project/software"
    - name: University coursework projects
      url: "/project/university"

author:
  name: "Wonyoung Jang"
  email: "contact@wonyoungjang.org"
