debug: true

defaultTheme: auto
env: production
title: Wonyoung Jang

assets:
  favicon: '/sitelogo.svg'
  favicon16x16: '/sitelogo.svg'
  favicon32x32: '/sitelogo.svg'
  apple_touch_icon: '/sitelogo.svg'

label:
  icon: '/sitelogo.svg'
  iconHeight: 24

home:
  title: Wonyoung Jang
  subtitle: Personal Website
  
  imageUrl: /sitelogo.svg
  imageTitle: WonyoungJang.org site logo
  imageHeight: 150px
  imageWidth: 150px
  
  buttons:
    - name: Software development projects
      url: "/project/software"
    - name: University coursework projects
      url: "/project/university"

author:
  name: "Wonyoung Jang"
  email: "contact@wonyoungjang.org"
