debug: false

defaultTheme: auto
env: production
title: Wonyoung Jang
description: "Wonyoung Jang's personal website"
dateFormat: January 2, 2006

assets:
  favicon: 'sitelogo.svg'

home:
  title: Wonyoung Jang
  tagline: exist **∧** time **→** create
  blurb: |
    If I'm existing and have the time, then I'll be creating stuff and sharing it with you.
    You're welcome to use anything you find here.

  projectButtons:
    - name: Software
      url: /projects/software
    - name: Design
      url: /projects/design
    - name: University
      url: /projects/university

  resourceButtons:
    - name: Layouts
      url: /resources/layouts
    - name: References
      url: /resources/references
    - name: Tokens
      url: /resources/tokens

author:
  name: Wonyoung Jang
  email: contact@wonyoungjang.org

fuseOpts:
  isCaseSensitive: false
  includeScore: true
  includeMatches: true
  minMatchCharLength: 1
  shouldSort: true
  findAllMatches: false
  keys: ["title", "permalink", "description", "summary", "content"]

  location: 0
  threshold: 0.6
  distance: 100
  ignoreLocation: false

  limit: 12