debug: false

defaultTheme: auto
env: production
title: Wonyoung Jang
dateFormat: January 2, 2006
description: "Wonyoung Jang's personal website"

assets:
  favicon: 'sitelogo.svg'

home:
  title: Wonyoung Jang
  subtitle: Personal Website

  buttons:
    - name: Software
      url: /projects/software
    - name: Design
      url: /projects/design
    - name: University coursework
      url: /projects/university

author:
  name: Wonyoung Jang
  email: contact@wonyoungjang.org

fuseOpts:
  # Basic
  isCaseSensitive: false
  includeScore: true
  includeMatches: true
  minMatchCharLength: 1
  shouldSort: true
  findAllMatches: false
  keys: ["title", "permalink", "summary", "content"]

  # Fuzzy matching
  location: 0
  threshold: 0.6
  distance: 100
  ignoreLocation: false

  limit: 5