debug: false

defaultTheme: auto
env: production
title: Wonyoung Jang

assets:
  favicon: '/favicon.ico'
  favicon16x16: '/favicon-16x16.webp'
  favicon32x32: '/favicon-32x32.webp'
  apple_touch_icon: '/apple-touch-icon.webp'

label:
  icon: '/favicon-32x32.webp'
  iconHeight: 24

socialIcons:
  - name: "GitHub"
    url: "https://github.com/wonyoung-jang"
  - name: "Ko-fi"
    url: "https://ko-fi.com/wonyoung_jang"
  - name: "Email"
    url: "mailto:contact@wonyoungjang.org"
  - name: "RSS"
    url: "/index.xml"

home:
  title: Wonyoung Jang
  subtitle: Personal Website
  
  imageUrl: /android-chrome-192x192.webp
  imageTitle: WonyoungJang.org site logo
  imageHeight: 150px
  imageWidth: 150px
  
  buttons:
    - name: Software development projects
      url: "/project/software"
    - name: University coursework projects
      url: "/project/university"

author:
  name: "Wonyoung Jang"
  email: "contact@wonyoungjang.org"
