baseURL: https://wonyoungjang.org/
languageCode: en-us
title: Wonyoung Jang
paginate: 9
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  profileMode:
    enabled: true
    title: WonyoungJang.org
    subtitle: "Welcome! Check out some of my projects: "

    imageUrl: /android-chrome-512x512.png
    imageWidth: 220 # custom size
    imageHeight: 220 # custom size
    imageTitle: WonyoungJang.org site logo
    
    buttons:
      - name: Software Development
        url: "/categories/software-development-projects"
      - name: University Coursework
        url: "/categories/university-coursework-projects"
     
  socialIcons:
    - name: "github"
      url: "https://github.com/wonyoung-jang"
    - name: "kofi"
      url: "https://ko-fi.com/wonyoung_jang"
    - name: "rss"
      url: "https://wonyoungjang.org/index.xml"
    - name: "email"
      url: "mailto:contact@wonyoungjang.org"

  label:
      text: 'Wonyoung Jang'
      icon: '/apple-touch-icon.png'

  env: production # To enable google analytics, opengraph, twitter-cards and schema.

  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true

  ShowToc: true
  TocOpen: false
  UseHugoToc: true
  
  defaultTheme: auto
  
  cover:
    linkFullImages: true

  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false

  author: "Wonyoung Jang"
  contact: "contact@wonyoungjang.org"

  feedlinks: true
  mobileMenu: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"

taxonomies:
  categories: "categories"

ignoreFiles:
  \.zip$

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 6
    ordered: false

googleAnalytics: G-RTMKJG4NFZ

minify:
  disableXML: true
  minifyOutput: true

sitemap:
  filename: sitemap.xml
  priority: 0.5
  changefreq: daily

related:
  includeNewer: true
  indices:
  - applyFilter: true
    name: categories
    weight: 80
  threshold: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

# sectionPagesMenu: main

menus:
  main:
    - identifier: Search
      name: Search
      pageRef: /search
      weight: 10
    - identifier: Projects # TODO This is a temporary hack
      name: Projects
      pageRef: /categories
      weight: 20
    - identifier: Software Development
      name: Software Development
      pageRef: /categories/software-development-projects
      parent: Projects
      weight: 1
    - identifier: University Coursework
      name: University Coursework
      pageRef: /categories/university-coursework-projects
      parent: Projects
      weight: 2
    - identifier: Graph
      name: Graph
      url: /graph/#/graph
      weight: 25
    - identifier: Archives
      name: Archives
      pageRef: /archives
      weight: 30
    - identifier: About
      name: About
      pageRef: /about
      weight: 50
    - identifier: Contact
      name: Contact
      pageRef: /contact
      weight: 60