baseURL: https://wonyoungjang.org/
languageCode: en-us
title: Wonyoung Jang

params:
  homeInfoParams:
    Title: WonyoungJang.org
    Content: "Welcome to my site! You can also find me at:"

  # Social Icons
  socialIcons:
    - name: "github"
      url: "https://github.com/wonyoung-jang"
    - name: "kofi"
      url: "https://ko-fi.com/wonyoung_jang"
    - name: "rss"
      url: "https://wonyoungjang.org/index.xml"
    - name: "email"
      url: "mailto:contact@wonyoungjang.org"

    # Maybe
    # - name: "behance"
    #   url: "https://www.behance.net/XXX"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # - name: "twitter"
    #   url: "https://twitter.com/XXX"
    
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  ShowToc: true

  feedlinks: true
  mobileMenu: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"

ignoreFiles:
  \.zip$

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 6
    ordered: false

services:
  googleAnalytics:  
    id: G-RTMKJG4NFZ

sitemap:
  filename: sitemap.xml
  priority: 0.5
  changefreq: daily

outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: about
      name: About
      url: /pages/about
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
    - identifier: contact
      name: Contact
      url: /pages/contact/
      weight: 50
