baseURL: https://wonyoung-jang.github.io
languageCode: en-us
title: Wonyoung Jang

params:
  homeInfoParams:
    Title: Wonyoung Jang
    Content: "Hello! You may find me at:"
  # Social Icons
  socialIcons:
    - name: "github"
      url: "https://github.com/wonyoung-jang"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # - name: "twitter"
    #   url: "https://twitter.com/XXX"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  feedlinks: true
  mobileMenu: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  ShowToc: true

ignoreFiles:
  \.zip$

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 6
    ordered: false

# Google Analytics 4 optional
#   env: #production
#   GoogleAnalytics: "G-00000XXXXX" 
#   sitemap:
#     changefreq: daily
#     filename: sitemap.xml
#     priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON
  #section:
  #  - HTML
  #  - RSS
  #  - JSON

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: about
      name: About
      url: /about
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
