baseURL: https://wonyoung-jang.github.io
languageCode: en-us
title: Wonyoung Jang
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Wonyoung Jang
    Content: "
      [Search: To search for projects and posts.](/search)


      [Categories: To browse posts by category.](/categories)
      

      [Archives: To browse posts by date.](/archives)


      [About: To learn more about me and this site.](/about)
    "
  # Social Icons
  socialIcons:
    - name: "github"
      url: "https://github.com/wonyoung-jang"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # - name: "twitter"
    #   url: "https://twitter.com/XXX"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Wonyoung Jang"
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  feedlinks: true
  mobileMenu: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  assets:
      disableHLJS: true
      favicon: TODO

# Google Analytics 4 optional
#  env: #production
#  GoogleAnalytics: "G-00000XXXXX" 
#  sitemap:
#    changefreq: daily
#    filename: sitemap.xml
#    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON
  #section:
  #  - HTML
  #  - RSS
  #  - JSON

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: about
      name: About
      url: /about
      weight: 40
    #- identifier: tags
    #  name: Tags
    #  url: /tags/
    #  weight: 30
