baseURL: https://wonyoungjang.org/
languageCode: en-us
title: Wonyoung Jang
paginate: 8

params:
  profileMode:
    enabled: true
    title: WonyoungJang.org
    imageUrl: /android-chrome-512x512.png
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Search
        url: "/search"
      - name: Categories
        url: "/categories"
      - name: Archives
        url: "/archives"
      - name: About
        url: "/about"
      - name: Contact
        url: "/contact"

  socialIcons:
    - name: "github"
      url: "https://github.com/wonyoung-jang"
    - name: "kofi"
      url: "https://ko-fi.com/wonyoung_jang"
    - name: "rss"
      url: "https://wonyoungjang.org/index.xml"
    - name: "email"
      url: "mailto:contact@wonyoungjang.org"
    # Maybe
    # - name: "behance"
    #   url: "https://www.behance.net/XXX"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # - name: "twitter"
    #   url: "https://twitter.com/XXX"

  env: production # To enable google analytics, opengraph, twitter-cards and schema.

  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowToc: true
  TocOpen: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  defaultTheme: auto

  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false

  author: "Wonyoung Jang"
  contact: "contact@wonyoungjang.org"

  feedlinks: true
  mobileMenu: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"

taxonomies:
  categories: "categories"

ignoreFiles:
  \.zip$

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 6
    ordered: false

googleAnalytics: G-RTMKJG4NFZ

minify:
  disableXML: true
  minifyOutput: true

sitemap:
  filename: sitemap.xml
  priority: 0.5
  changefreq: daily

related:
  includeNewer: true
  indices:
  - applyFilter: true
    name: categories
    weight: 80
  threshold: 20

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
    - identifier: about
      name: About
      url: /about/
      weight: 50
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 51
