name: github pages
on:
  push:
    branches:
      - main # Set a branch to deploy
  pull_request:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout Code 
        uses: actions/checkout@v3.2.0
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Build
        run: hugo --minify
      - name: Logseq Publish 🚩
        uses: logseq/publish-spa@main
        with:
          graph-directory: ./logseq
          output-directory: ./public/graph
          version: nightly
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.119.0'
          extended: true
      #- name: Deploy
      #  uses: peaceiris/actions-gh-pages@v3.9.0
      #  if: github.ref == 'refs/heads/main'
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./public
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./public
